# Generated by Django 5.1.6 on 2025-12-12 12:19

import utils.helpers.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('location', models.CharField(help_text='Where are you coming to the hub from', max_length=255, verbose_name='location')),
                ('reason', models.TextField(help_text='Why do you want to come and use the hub', verbose_name='reason')),
                ('role', models.CharField(help_text='Describe your role in the ecosystem (e.g. Developer, founder, creator…)', max_length=255, verbose_name='role')),
                ('contribution', models.TextField(help_text='Please share how you contribute to Ethereum', verbose_name='contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub Registration',
                'verbose_name_plural': 'Hub Registrations',
                'indexes': [models.Index(fields=['-created_at'], name='hub_reg_created_at_idx'), models.Index(fields=['email'], name='hub_reg_email_idx')],
            },
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
    ]
