# Generated by Django 5.1.6 on 2025-12-12 12:40

import django.db.models.deletion
import utils.helpers.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20, verbose_name='status')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='check in time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='check out time')),
                ('purpose', models.TextField(blank=True, help_text='Purpose of visit', null=True, verbose_name='purpose')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
                'ordering': ['-check_in_time'],
            },
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HubSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Hub', max_length=255, verbose_name='space name')),
                ('total_capacity', models.IntegerField(default=50, help_text='Total number of people the hub can accommodate', verbose_name='total capacity')),
                ('current_occupancy', models.IntegerField(default=0, help_text='Current number of people in the hub', verbose_name='current occupancy')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this space is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub Space',
                'verbose_name_plural': 'Hub Spaces',
            },
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name='hubregistration',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins', null=True, verbose_name='admin notes'),
        ),
        migrations.AddField(
            model_name='hubregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='hubregistration',
            index=models.Index(fields=['status'], name='hub_reg_status_idx'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='registration',
            field=models.ForeignKey(help_text='The registration this check-in belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='hub.hubregistration'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='space',
            field=models.ForeignKey(help_text='The space being used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='hub.hubspace'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['-check_in_time'], name='checkin_time_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['status'], name='checkin_status_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['registration'], name='checkin_registration_idx'),
        ),
    ]
