# Generated by Django 5.1.6 on 2025-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_checkin_hubspace_hubregistration_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_out', 'Checked Out')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
