# Generated by Django 5.1.6 on 2025-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_add_checked_out_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubregistration',
            name='expected_duration_hours',
            field=models.IntegerField(default=4, help_text='Expected duration of visit in hours', verbose_name='expected duration hours'),
        ),
        migrations.AddField(
            model_name='hubregistration',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='Preferred date for visiting the hub', null=True, verbose_name='preferred date'),
        ),
        migrations.AddField(
            model_name='hubregistration',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='Preferred time for visiting the hub', null=True, verbose_name='preferred time'),
        ),
        migrations.AddIndex(
            model_name='hubregistration',
            index=models.Index(fields=['preferred_date', 'preferred_time'], name='hub_reg_date_time_idx'),
        ),
    ]
