# Generated by Django 5.1.6 on 2025-12-23 11:36

import utils.helpers.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_hubregistration_expected_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the blocked period (inclusive)', verbose_name='start date')),
                ('end_date', models.DateField(help_text='End date of the blocked period (inclusive)', verbose_name='end date')),
                ('reason', models.TextField(blank=True, help_text="Reason for blocking these dates (e.g., 'Holiday', 'Maintenance', etc.)", null=True, verbose_name='reason')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this blocked date range is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked Date Range',
                'verbose_name_plural': 'Blocked Date Ranges',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='blocked_date_range_idx'), models.Index(fields=['is_active'], name='blocked_date_range_active_idx')],
            },
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
    ]
