# Generated by Django 5.1.14 on 2026-04-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_checkin_status_checkin_time_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkin',
            new_name='checkin_status_time_idx',
            old_name='checkin_status_checkin_time_idx',
        ),
    ]
