# Generated by Django 5.1.6 on 2025-12-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0011_participant_venue'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['-created_at'], name='participant_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='participant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['registration'], name='participant_registration_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['course'], name='participant_course_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['status'], name='participant_status_idx'),
        ),
    ]
