# Generated by Django 5.1.6 on 2026-01-10 13:14

import django.db.models.deletion
import utils.helpers.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0012_participant_participant_created_at_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedWeb3Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email for lookup (required even if participant exists)', max_length=255, unique=True, verbose_name='email address')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this approval', null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(blank=True, help_text="Reference to the participant (optional if participant doesn't exist yet)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_web3_status', to='cohort.participant')),
            ],
            options={
                'verbose_name': 'Approved Web3 Participant',
                'verbose_name_plural': 'Approved Web3 Participants',
                'indexes': [models.Index(fields=['email'], name='approved_web3_email_idx'), models.Index(fields=['-created_at'], name='approved_web3_created_at_idx')],
            },
            bases=(utils.helpers.models.base.BaseModelBaseMixin, models.Model),
        ),
    ]
