# Generated by Django 5.1.14 on 2026-04-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0013_approvedweb3participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('cohort', models.CharField(max_length=255, verbose_name='cohort')),
                ('rescheduled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='reschedule_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='score')),
                ('breakdown', models.JSONField(blank=True, null=True, verbose_name='breakdown')),
                ('date_taken', models.DateTimeField(verbose_name='date taken')),
                ('passed', models.BooleanField(default=False, verbose_name='passed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cohort.participant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant'], name='assessment_participant_idx')],
            },
        ),
    ]
