# Generated by Django 5.1.14 on 2026-04-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0014_assessmentreschedule_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreschedule',
            name='participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_reschedule', to='cohort.participant'),
        ),
        migrations.AlterField(
            model_name='assessmentreschedule',
            name='email',
            field=models.EmailField(help_text='Denormalized copy of participant email for reporting.', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(help_text='Collected on the registration form (e.g. male, female, other); exposed via Participant create API.', max_length=20, null=True, verbose_name='gender'),
        ),
    ]
