# Generated by Django 5.1.6 on 2025-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_discountcode_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='offset',
            field=models.IntegerField(default=1, help_text='maximum number of users that can use the code'),
        ),
    ]
