# Generated by Django 5.1.6 on 2025-09-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_discountcode_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=127)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('participant_id', models.IntegerField(blank=True, help_text='ID of the participant who used the code', null=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='payment.discountcode')),
            ],
            options={
                'indexes': [models.Index(fields=['discount_code', 'user_email'], name='discount_usage_idx'), models.Index(fields=['user_email'], name='user_email_idx')],
                'unique_together': {('discount_code', 'user_email')},
            },
        ),
    ]
